package com.raybiztech.appraisals.business;

public enum Status {
NEW,IN_PROCESS,HOLD,COMPLETED,CANCEL,REJECTED,OFFERED,RESCHEDULED,NO_SHOW,DID_NOT_JOIN,REPROCESS,OFFER_CANCELLED,JOINED,ADD_COMMENTS;
}
