package com.raybiztech.expenseManagement.business;

import java.io.Serializable;

import com.raybiztech.appraisals.business.EmpDepartment;
import com.raybiztech.appraisals.business.Employee;
import com.raybiztech.assetmanagement.business.VendorDetails;
import com.raybiztech.date.Date;
import com.raybiztech.date.Second;
import com.raybiztech.projectmanagement.business.Project;
import com.raybiztech.projectmanagement.invoice.lookup.Currency;

public class ExpenseFormAudit implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7511963204494066554L;
	
	private Long id;
	private Long formId;
	private String expenseNumber;
	private Employee toEmployee;
	private ExpenseCategory category;
	private ExpenseSubCategory subCategory;
	private EmpDepartment department;
	private Project project;
	private VendorDetails vendor;
	private String purpose;
	private Date expenditureDate;
	private String country;
	private Currency currency;
	private String paymentMode;
	private CreditCard creditCardDetails;
	private String chequeNumber;
	private Date chequeDate;
	private String voucherNumber;
	private String amount;
	private String saltKey;
	private String description;
	private Boolean isReimbursable;
	private String paymentStatus;
	private Employee modifiedBy;
	private Second modifiedDate;
	private String persistType;
	private String invoiceNumber;
	private Boolean isAutogenerated;
	
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getFormId() {
		return formId;
	}
	public void setFormId(Long formId) {
		this.formId = formId;
	}
	public Employee getToEmployee() {
		return toEmployee;
	}
	public void setToEmployee(Employee toEmployee) {
		this.toEmployee = toEmployee;
	}
	public ExpenseCategory getCategory() {
		return category;
	}
	public void setCategory(ExpenseCategory category) {
		this.category = category;
	}
	public ExpenseSubCategory getSubCategory() {
		return subCategory;
	}
	public void setSubCategory(ExpenseSubCategory subCategory) {
		this.subCategory = subCategory;
	}
	public EmpDepartment getDepartment() {
		return department;
	}
	public void setDepartment(EmpDepartment department) {
		this.department = department;
	}
	public Project getProject() {
		return project;
	}
	public void setProject(Project project) {
		this.project = project;
	}
	public VendorDetails getVendor() {
		return vendor;
	}
	public void setVendor(VendorDetails vendor) {
		this.vendor = vendor;
	}
	public String getPurpose() {
		return purpose;
	}
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}
	public Date getExpenditureDate() {
		return expenditureDate;
	}
	public void setExpenditureDate(Date expenditureDate) {
		this.expenditureDate = expenditureDate;
	}
	public Currency getCurrency() {
		return currency;
	}
	public void setCurrency(Currency currency) {
		this.currency = currency;
	}
	public String getPaymentMode() {
		return paymentMode;
	}
	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}
	public String getChequeNumber() {
		return chequeNumber;
	}
	public void setChequeNumber(String chequeNumber) {
		this.chequeNumber = chequeNumber;
	}
	public Date getChequeDate() {
		return chequeDate;
	}
	public void setChequeDate(Date chequeDate) {
		this.chequeDate = chequeDate;
	}
	public String getVoucherNumber() {
		return voucherNumber;
	}
	public void setVoucherNumber(String voucherNumber) {
		this.voucherNumber = voucherNumber;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getSaltKey() {
		return saltKey;
	}
	public void setSaltKey(String saltKey) {
		this.saltKey = saltKey;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Boolean getIsReimbursable() {
		return isReimbursable;
	}
	public void setIsReimbursable(Boolean isReimbursable) {
		this.isReimbursable = isReimbursable;
	}
	public Employee getModifiedBy() {
		return modifiedBy;
	}
	public void setModifiedBy(Employee modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Second getModifiedDate() {
		return modifiedDate;
	}
	public void setModifiedDate(Second modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public String getPersistType() {
		return persistType;
	}
	public void setPersistType(String persistType) {
		this.persistType = persistType;
	}
	public String getExpenseNumber() {
		return expenseNumber;
	}
	public void setExpenseNumber(String expenseNumber) {
		this.expenseNumber = expenseNumber;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
	this.country = country;
	}
	public CreditCard getCreditCardDetails() {
		return creditCardDetails;
	}
	public void setCreditCardDetails(CreditCard creditCardDetails) {
		this.creditCardDetails = creditCardDetails;
	}
	
	public String getPaymentStatus() {
		return paymentStatus;
	}
	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}
	
    public String getInvoiceNumber() {
		return invoiceNumber;
	}
	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}
	@Override
	public String toString() {
		return "ExpenseFormAudit [id=" + id + ", formId=" + formId + ", expenseNumber=" + expenseNumber
				+ ", toEmployee=" + toEmployee + ", category=" + category + ", subCategory=" + subCategory
				+ ", department=" + department + ", project=" + project + ", vendor=" + vendor + ", purpose=" + purpose
				+ ", expenditureDate=" + expenditureDate + ", country=" + country + ", currency=" + currency
				+ ", paymentMode=" + paymentMode + ", creditCardDetails=" + creditCardDetails + ", chequeNumber="
				+ chequeNumber + ", chequeDate=" + chequeDate + ", voucherNumber=" + voucherNumber + ", amount="
				+ amount + ", saltKey=" + saltKey + ", description=" + description + ", isReimbursable="
				+ isReimbursable + ", paymentStatus=" + paymentStatus + ", modifiedBy=" + modifiedBy + ", modifiedDate="
				+ modifiedDate + ", persistType=" + persistType + "]";
	}
	public Boolean getIsAutogenerated() {
		return isAutogenerated;
	}
	public void setIsAutogenerated(Boolean isAutogenerated) {
		this.isAutogenerated = isAutogenerated;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
