package com.raybiztech.expenseManagement.dto;

import com.raybiztech.appraisals.dto.EmployeeDTO;
import com.raybiztech.assetmanagement.dto.VendorDto;
import com.raybiztech.projectmanagement.dto.ProjectDTO;

public class ExpenseFormDto {
	
	private Long formId;
	private String expenseNumber;
	private EmployeeDTO toEmployee;
	private Long categoryId;
	private String categoryName;
	private Long subCategoryId;
	private String subCategoryName;
	private Long deptId;
	private String deptName;
	private ProjectDTO project;
	private VendorDto vendor;
	private String purpose;
	private String expenditureDate;
	private String country;
	private Long currencyId;
	private String currencyType;
	private String paymentMode;
	private CreditCardDto creditCardDetails;
	private String chequeNumber;
	private String chequeDate;
	private String voucherNumber;
	private String amount;
	private String description;
	private Boolean isReimbursable;
	private Long empId;
	private String saltKey;
	private String paymentStatus;
	private String remainingAmount;
	private String amountInINR;
	private String createdBy;
	private String createdDate;
	private String updatedBy;
	private String updatedDate;
	private String invoiceNumber;
	private Boolean isAutogenerated;
	
	
	public Long getFormId() {
		return formId;
	}
	public void setFormId(Long formId) {
		this.formId = formId;
	}
	public Long getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	public String getCategoryName() {
		return categoryName;
	}
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	public Long getSubCategoryId() {
		return subCategoryId;
	}
	public void setSubCategoryId(Long subCategoryId) {
		this.subCategoryId = subCategoryId;
	}
	public String getSubCategoryName() {
		return subCategoryName;
	}
	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}
	public Long getDeptId() {
		return deptId;
	}
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}
	public String getDeptName() {
		return deptName;
	}
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
	public String getPurpose() {
		return purpose;
	}
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}
	public String getExpenditureDate() {
		return expenditureDate;
	}
	public void setExpenditureDate(String expenditureDate) {
		this.expenditureDate = expenditureDate;
	}
	public Long getCurrencyId() {
		return currencyId;
	}
	public void setCurrencyId(Long currencyId) {
		this.currencyId = currencyId;
	}
	public String getCurrencyType() {
		return currencyType;
	}
	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}
	public String getPaymentMode() {
		return paymentMode;
	}
	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}
	public String getChequeNumber() {
		return chequeNumber;
	}
	public void setChequeNumber(String chequeNumber) {
		this.chequeNumber = chequeNumber;
	}
	public String getChequeDate() {
		return chequeDate;
	}
	public void setChequeDate(String chequeDate) {
		this.chequeDate = chequeDate;
	}
	public String getVoucherNumber() {
		return voucherNumber;
	}
	public void setVoucherNumber(String voucherNumber) {
		this.voucherNumber = voucherNumber;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Boolean getIsReimbursable() {
		return isReimbursable;
	}
	public void setIsReimbursable(Boolean isReimbursable) {
		this.isReimbursable = isReimbursable;
	}
	public Long getEmpId() {
		return empId;
	}
	public void setEmpId(Long empId) {
		this.empId = empId;
	}
	public String getSaltKey() {
		return saltKey;
	}
	public void setSaltKey(String saltKey) {
		this.saltKey = saltKey;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public String getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}
	public String getExpenseNumber() {
		return expenseNumber;
	}
	public void setExpenseNumber(String expenseNumber) {
		this.expenseNumber = expenseNumber;
	}
	
	public String getCountry() {
		return country;
	}
	
	public void setCountry(String country) {
	this.country = country;
	}
	public CreditCardDto getCreditCardDetails() {
		return creditCardDetails;
	}
	public void setCreditCardDetails(CreditCardDto creditCardDetails) {
		this.creditCardDetails = creditCardDetails;
	}
	public EmployeeDTO getToEmployee() {
		return toEmployee;
	}
	public void setToEmployee(EmployeeDTO toEmployee) {
		this.toEmployee = toEmployee;
	}
	public ProjectDTO getProject() {
		return project;
	}
	public void setProject(ProjectDTO project) {
		this.project = project;
	}
	public VendorDto getVendor() {
		return vendor;
	}
	public void setVendor(VendorDto vendor) {
		this.vendor = vendor;
	}
	public String getPaymentStatus() {
		return paymentStatus;
	}
	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}
	public String getRemainingAmount() {
		return remainingAmount;
	}
	public void setRemainingAmount(String remainingAmount) {
		this.remainingAmount = remainingAmount;
	}
	public String getAmountInINR() {
		return amountInINR;
	}
	public void setAmountInINR(String amountInINR) {
		this.amountInINR = amountInINR;
	}
	public String getInvoiceNumber() {
		return invoiceNumber;
	}
	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}
	public Boolean getIsAutogenerated() {
		return isAutogenerated;
	}
	public void setIsAutogenerated(Boolean isAutogenerated) {
		this.isAutogenerated = isAutogenerated;
	}
	
	
	
	
}
